utilityBarLinks/force-app/main/default/objects/Utility_Bar_Link__mdt/Utility_Bar_Link__mdt.object-meta.xml
<CustomObject>
    <description>This metadata type allows you to set external links for a particular user, controlled by the users Id</description>
    <label>Utility Bar Link</label>
    <pluralLabel>Utility Bar Links</pluralLabel>
</CustomObject>

utilityBarLinks/force-app/main/default/objects/Utility_Bar_Link__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determined whether or not the link is active and available for showing.</description>
    <inlineHelpText>Determined whether or not the link is active and available for showing.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

utilityBarLinks/force-app/main/default/objects/Utility_Bar_Link__mdt/fields/Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Link_URL__c</fullName>
    <description>Stores the link URL.</description>
    <inlineHelpText>Stores the link URL.</inlineHelpText>
    <label>Link URL</label>
    <type>Url</type>
</CustomField>

utilityBarLinks/force-app/main/default/objects/Utility_Bar_Link__mdt/fields/Open_In_Console_Tab__c.field-meta.xml
<CustomField>
    <fullName>Open_In_Console_Tab__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If used in a console app, allows users to open said links with in the salesforce window.</description>
    <inlineHelpText>If used in a console app, allows users to open said links with in the salesforce window.</inlineHelpText>
    <label>Open In Console Tab</label>
    <type>Checkbox</type>
</CustomField>

utilityBarLinks/force-app/main/default/objects/Utility_Bar_Link__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Sets the order in which a link is displayed. Lower numbers indicate that the link should be displayed first.</description>
    <inlineHelpText>Sets the order in which a link is displayed. Lower numbers indicate that the link should be displayed first.</inlineHelpText>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

utilityBarLinks/force-app/main/default/classes/External_Links_Controller.cls
/* Documentation Station */

public with sharing class External_Links_Controller {
    @AuraEnabled
    public static List<Utility_Bar_Link__mdt> getExternalLinks(){
        try {
            return[SELECT MasterLabel,Link_URL__c,Open_in_console_tab__c FROM Utility_Bar_Link__mdt WHERE Active__c = TRUE ORDER BY Order__c ASC];
            
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}